### ISSUE TITLE
[REQUEST] Change how often this exporter scrapes the PostgreSQL database

### ISSUE THREAD

**Issue by mdenend** [wrouesnel/postgres_exporter#277]
I am planning on running this against a production database that I expect to be heavily taxed with other queries, but I am not very familiar with Go at all, so I have a couple of questions:

1. How often does the query run against the database?
2. Is there a way to increase the minimum time between queries to the database, preferably without rebuilding the exporter?

If there isn't a way to increase the minimum time between queries without altering the code, may I suggest adding an option to set a minimum query interval to ensure not too many queries are running, which would delay a query from happening again for at least a certain time? 

I think a simple option would be something like MINIMUM_QUERY_INTERVAL=1.2345 where 1.2345 is time in seconds.

**Comment by mdenend** [comment]
OK. So I think I answered question 1. When I ran in Prometheus `increase(pg_exporter_scrapes_total[1m])`, I got 2. So looks like it's every 30 seconds. 

Still not sure about question 2. However, if we're running taxing PostgreSQL functions that takes seconds, we may want to delay it further. Or... if someone wants more granular metrics, we may want to decrease the time.

 I'm OK rebuilding the container if someone shows me where to adjust this delay, but I still think this should be configurable.

**Comment by wrouesnel** [comment]
Ultimately it needs some sort of cache. The most correct way to do it is queue up connections that happen while we're scraping the DB, and return them all at once, hopefully reducing the number of simultaneous connections.

**Comment by wrouesnel** [comment]
PR #319 should fix this issue and is now merged to master.

`queries.yml` supports a `cache_seconds` flag against each namespace to use old data. The included `queries.yml` is now doing this for `pg_database`.

**Comment by vineet-raja-covergo** [comment]
The original question is still not answered. 
There is still no way (config settings, or command line arguments, or env vars etc) to control the frequency of scraping the database.
And it is indeed every 30s or so it seems.

The [answer](https://github.com/prometheus-community/postgres_exporter/issues/277#issuecomment-548372040) above is about the frequency of custom queries.

**Comment by SuperQ** [comment]
The exporter does not control scrape frequency. This is handled by Prometheus. The exporter queries as often as you scrape.
